language : c

os :
 - linux
 - osx

install:
 - source .travis/install.sh

script :
 - make test TF=NO_TEST && make unit_tests
 - ~/42FileChecker/42FileChecker.sh --project "libft" --path "$(pwd)"
 - cat ~/42FileChecker/.mymoulitest
 - cat ~/42FileChecker/.mylibftunittest
 - cat ~/42FileChecker/.mymaintest_libft
