language : c

os :
# - linux
 - osx

sudo : required

install:
 - echo installing
 - source ./.travis/install.sh
 - echo 'install done'

script :
 - make
 - make
 - make re
 - make test TF=STRSUB #&& make unit_tests
 - make libft
 - ~/42FileChecker/42FileChecker.sh 
   --project "libft" 
   --path "$(pwd)/libft"
   --no-norminette
 - cat ~/42FileChecker/.mymakefile
 - cat ~/42FileChecker/.mymoulitest
 - cat ~/42FileChecker/.mylibftunittest
 - cat ~/42FileChecker/.mymaintest_libft
