os : osx
language : c
before_install :
 - sudo apt-get install mutt
before_script :
 - git clone https://github.com/jgigault/42FileChecker ~/42FileChecker
script :
 - cd ~/42FileChecker && bash ./42FileChecker.sh
