language : c

before_install :
 - echo '\n42FileChecker installation starting\n'
 - git clone https://github.com/jgigault/42FileChecker ~/42FileChecker
 - echo '\n42FileChecker installation complete\n'

script :
 - make
 - chmod a+x ~/42FileChecker/42FileChecker.sh
 - ~/42FileChecker/42FileChecker.sh --project "libft" --path "$(pwd)"
 - cat ~/42FileChecker/.mymoulitest
 - cat ~/42FileChecker/.mylibftunittest
 - cat ~/42FileChecker/.mymaintest_libft
