language : c

before_install :
 - echo '\n42FileChecker installation starting\n'
 - git clone https://github.com/jgigault/42FileChecker ~/42FileChecker
 - echo '\n42FileChecker installation complete\n'

script :
 - make
 - bash ~/42FileChecker/42FileChecker.sh --project "libft" --path "."
