language : c

matrix :
 include :
  - os : linux
    sudo : required
  - os : osx

install:
 - echo installing
 - source ./.travis/install.sh
 - echo 'install done'

script :
 - make test TF=NO_TEST && make unit_tests
 - >
   ~/42FileChecker/42FileChecker.sh 
   --project "libft" 
   --path "$(pwd)/libft"
   --no-norminette
 - cat ~/42FileChecker/.mymoulitest
 - cat ~/42FileChecker/.mylibftunittest
 - cat ~/42FileChecker/.mymaintest_libft
