os : osx

language : c

before_install :
 - git clone https://github.com/jgigault/42FileChecker ~/42FileChecker
 - chmod a+x ~/42FileChecker/42FileChecker.sh

script :
 - make
 - ~/42FileChecker/42FileChecker.sh --project "libft" --path "$(pwd)"
 - cat ~/42FileChecker/.mymoulitest
 - cat ~/42FileChecker/.mylibftunittest
 - cat ~/42FileChecker/.mymaintest_libft
